/*******************************************************************************
 * Copyright 2009, Clark N. Hobbie
 * 
 * This file is part of the CLIPC library.
 * 
 * The CLIPC library is free software; you can redistribute it and/or modify it
 * under the terms of the Lesser GNU General Public License as published by
 * the Free Software Foundation; either version 2.1 of the License, or (at
 * your option) any later version.
 * 
 * The CLIPC library is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE.  See the Lesser GNU General Public
 * License for more details.
 * 
 * You should have received a copy of the Lesser GNU General Public License
 * along with the CLIP library; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
 * 
 *******************************************************************************/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lts_ipc_IPCPackage */

#ifndef _Included_com_lts_ipc_IPCPackage
#define _Included_com_lts_ipc_IPCPackage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lts_ipc_IPCPackage
 * Method:    initializeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lts_ipc_IPCPackage_initializeNative
  (JNIEnv *, jclass);

/*
 * Class:     com_lts_ipc_IPCPackage
 * Method:    setValue
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_lts_ipc_IPCPackage_setValue
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_lts_ipc_IPCPackage
 * Method:    createBuffer
 * Signature: (I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_lts_ipc_IPCPackage_createBuffer
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
